services:
  server:
    image: ashwinr10/easystay-server
    container_name: easystay-server
    ports:
      - "3000:3000"
    env_file:
      - ./Server/.env
    restart: always

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
      args:
        VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        VITE_CURRENCY: ${VITE_CURRENCY}
    image: ashwinr10/easystay-client
    ports:
      - "3001:80"